# permissions for end users to edit cronhorizontalpodautoscalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cronhorizontalpodautoscaler-editor-role
rules:
- apiGroups:
  - autoscaling.example.com
  resources:
  - cronhorizontalpodautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling.example.com
  resources:
  - cronhorizontalpodautoscalers/status
  verbs:
  - get
