# permissions for end users to view cronhorizontalpodautoscalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cronhorizontalpodautoscaler-viewer-role
rules:
- apiGroups:
  - autoscaling.example.com
  resources:
  - cronhorizontalpodautoscalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - autoscaling.example.com
  resources:
  - cronhorizontalpodautoscalers/status
  verbs:
  - get
